# Generated by Django 5.1.6 on 2025-02-28 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_noticia_archivo_fecha_noticia_archivo_imagen"),
        ("core", "0003_remove_noticia_fecha_publicacion_and_more"),
        ("core", "0004_entidad_noticia_resumen_alter_noticia_categoria_and_more"),
        ("core", "0005_noticia_markdown"),
        ("core", "0006_noticia_archivo_titulo_noticia_meta_imagen_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("enlace", models.URLField(unique=True)),
                ("archivo_url", models.URLField(blank=True, null=True)),
                ("fuente", models.CharField(max_length=255, null=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("politica", "Política"),
                            ("economia", "Economía"),
                            ("seguridad", "Seguridad"),
                            ("salud", "Salud"),
                            ("educacion", "Educación"),
                            ("otros", "Otros"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fecha_agregado", models.DateTimeField(auto_now_add=True)),
                (
                    "agregado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("archivo_fecha", models.DateTimeField(blank=True, null=True)),
                ("archivo_imagen", models.URLField(blank=True, null=True)),
                ("resumen", models.TextField(blank=True, null=True)),
                ("markdown", models.TextField(blank=True, null=True)),
                (
                    "archivo_titulo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("meta_imagen", models.URLField(blank=True, null=True)),
                (
                    "meta_titulo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opinion",
                    models.CharField(
                        choices=[
                            ("buena", "Buena noticia"),
                            ("mala", "Mala noticia"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha_voto", models.DateTimeField(auto_now_add=True)),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="core.noticia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "noticia")},
            },
        ),
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("organizacion", "Organización"),
                            ("lugar", "Lugar"),
                            ("otro", "Otro"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticiaEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentimiento",
                    models.CharField(
                        choices=[
                            ("positivo", "Positivo"),
                            ("negativo", "Negativo"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.entidad"
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entidades",
                        to="core.noticia",
                    ),
                ),
            ],
            options={
                "unique_together": [("noticia", "entidad")],
            },
        ),
    ]
