# Generated by Django 5.0 on 2025-02-18 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("enlace", models.URLField(unique=True)),
                ("archivo_url", models.URLField(blank=True, null=True)),
                ("fecha_publicacion", models.DateField()),
                ("fuente", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("politica", "Política"),
                            ("economia", "Economía"),
                            ("salud", "Salud"),
                            ("educacion", "Educación"),
                            ("otros", "Otros"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fecha_agregado", models.DateTimeField(auto_now_add=True)),
                (
                    "agregado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opinion",
                    models.CharField(
                        choices=[
                            ("buena", "Buena noticia"),
                            ("mala", "Mala noticia"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha_voto", models.DateTimeField(auto_now_add=True)),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="core.noticia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": [("usuario", "noticia")],
            },
        ),
    ]
