# Generated by Django 5.0 on 2025-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
 ***REMOVED***

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="archivo_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="archivo_imagen",
            field=models.URLField(blank=True, null=True),
        ),
 ***REMOVED***
