# Generated by Django 5.1.6 on 2025-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_noticia_archivo_fecha_noticia_archivo_imagen"),
 ***REMOVED***

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="fecha_publicacion",
        ),
        migrations.AlterField(
            model_name="noticia",
            name="fuente",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="titulo",
            field=models.CharField(max_length=255, null=True),
        ),
 ***REMOVED***
