# Generated by Django 5.1.6 on 2025-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_noticia_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="archivo_titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="meta_imagen",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="meta_titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
