# Generated by Django 5.1.6 on 2025-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0001_squashed_0006_noticia_archivo_titulo_noticia_meta_imagen_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="fecha_noticia",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
