# Generated by Django 5.1.6 on 2025-02-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_noticia_fecha_publicacion_and_more"),
    ]
    operations = [
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("organizacion", "Organización"),
                            ("lugar", "Lugar"),
                            ("otro", "Otro"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="noticia",
            name="resumen",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("politica", "Política"),
                    ("economia", "Economía"),
                    ("seguridad", "Seguridad"),
                    ("salud", "Salud"),
                    ("educacion", "Educación"),
                    ("otros", "Otros"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="NoticiaEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentimiento",
                    models.CharField(
                        choices=[
                            ("positivo", "Positivo"),
                            ("negativo", "Negativo"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.entidad"
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entidades",
                        to="core.noticia",
                    ),
                ),
            ],
            options={
                "unique_together": [("noticia", "entidad")],
            },
        ),
    ]
