# Generated by Django 5.1.6 on 2025-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_entidad_noticia_resumen_alter_noticia_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="markdown",
            field=models.TextField(blank=True, null=True),
        ),
    ]
