# Generated by Django 5.1.7 on 2025-12-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_noticia_fecha_noticia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voto",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="archivo_fecha",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="archivo_imagen",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="archivo_titulo",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="archivo_url",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="fecha_noticia",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="fuente",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="markdown",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="resumen",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="titulo",
        ),
        migrations.AddField(
            model_name="noticia",
            name="meta_descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voto",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session ID for anonymous votes",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="agregado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted (null if anonymous)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="enlace",
            field=models.URLField(help_text="Original news article URL", unique=True),
        ),
        migrations.AlterField(
            model_name="voto",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user (null if anonymous)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="voto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("usuario__isnull", False)),
                fields=("usuario", "noticia"),
                name="unique_user_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="voto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key", "noticia"),
                name="unique_session_vote",
            ),
        ),
    ]
