# Generated by Django 5.1.7 on 2025-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_mvp_cleanup_anonymous_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="captured_html",
            field=models.TextField(
                blank=True,
                help_text="Full HTML captured from user's browser",
                null=True,
            ),
        ),
    ]
