# Generated by Django 5.1.7 on 2025-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_noticia_captured_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="markdown",
            field=models.TextField(
                blank=True,
                help_text="Markdown version of article (generated from captured_html)",
                null=True,
            ),
        ),
    ]
