# Generated by Django 5.1.7 on 2025-12-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_noticia_markdown"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="markdown",
        ),
    ]
