# Generated by Django 5.1.7 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_noticia_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="meta_imagen",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
