# Generated by Django 5.1.7 on 2026-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_noticia_meta_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO-friendly URL slug",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
