# Generated by Django 5.1.7 on 2026-01-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_noticia_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterClusterRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("n_voters", models.IntegerField(default=0)),
                ("n_noticias", models.IntegerField(default=0)),
                ("n_clusters", models.IntegerField(default=0)),
                (
                    "computation_time",
                    models.FloatField(
                        blank=True, help_text="Computation time in seconds", null=True
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Clustering parameters (k, time_window, etc.)",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="core_voterc_created_8a8ab9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoterCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_id",
                    models.IntegerField(help_text="Cluster identifier within this run"),
                ),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("base", "Base cluster"),
                            ("group", "Group cluster"),
                            ("subgroup", "Subgroup cluster"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(help_text="Number of voters in this cluster"),
                ),
                (
                    "centroid_x",
                    models.FloatField(help_text="X coordinate of cluster center"),
                ),
                (
                    "centroid_y",
                    models.FloatField(help_text="Y coordinate of cluster center"),
                ),
                (
                    "consensus_score",
                    models.FloatField(
                        blank=True,
                        help_text="Within-cluster agreement (0-1)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional cluster metadata (radius, variance, etc.)",
                    ),
                ),
                (
                    "parent_cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent cluster for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclusters",
                        to="core.votercluster",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="core.voterclusterrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoterProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_type",
                    models.CharField(
                        choices=[
                            ("session", "Session-based voter"),
                            ("user", "Authenticated user"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "voter_id",
                    models.CharField(
                        help_text="Session key or user ID", max_length=255
                    ),
                ),
                (
                    "projection_x",
                    models.FloatField(help_text="X coordinate in PCA space"),
                ),
                (
                    "projection_y",
                    models.FloatField(help_text="Y coordinate in PCA space"),
                ),
                (
                    "n_votes_cast",
                    models.IntegerField(help_text="Number of votes cast by this voter"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projections",
                        to="core.voterclusterrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClusterVotingPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_buena", models.IntegerField(default=0)),
                ("count_mala", models.IntegerField(default=0)),
                ("count_neutral", models.IntegerField(default=0)),
                (
                    "consensus_score",
                    models.FloatField(
                        blank=True,
                        help_text="Degree of agreement on this noticia (0-1)",
                        null=True,
                    ),
                ),
                (
                    "majority_opinion",
                    models.CharField(
                        blank=True, help_text="buena/mala/neutral", max_length=10
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.noticia"
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_patterns",
                        to="core.votercluster",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cluster", "consensus_score"],
                        name="core_cluste_cluster_338ec9_idx",
                    ),
                    models.Index(
                        fields=["cluster", "majority_opinion"],
                        name="core_cluste_cluster_b4ab55_idx",
                    ),
                ],
                "unique_together": {("cluster", "noticia")},
            },
        ),
        migrations.CreateModel(
            name="VoterClusterMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_type", models.CharField(max_length=10)),
                ("voter_id", models.CharField(max_length=255)),
                (
                    "distance_to_centroid",
                    models.FloatField(
                        blank=True,
                        help_text="Euclidean distance to cluster centroid",
                        null=True,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.votercluster",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["voter_type", "voter_id"],
                        name="core_voterc_voter_t_c2a092_idx",
                    ),
                    models.Index(
                        fields=["cluster"], name="core_voterc_cluster_3c4f1b_idx"
                    ),
                ],
                "unique_together": {("cluster", "voter_type", "voter_id")},
            },
        ),
        migrations.AddIndex(
            model_name="votercluster",
            index=models.Index(
                fields=["run", "cluster_type"], name="core_voterc_run_id_b20989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votercluster",
            index=models.Index(
                fields=["run", "consensus_score"], name="core_voterc_run_id_123fd6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="votercluster",
            unique_together={("run", "cluster_type", "cluster_id")},
        ),
        migrations.AddIndex(
            model_name="voterprojection",
            index=models.Index(
                fields=["voter_type", "voter_id"], name="core_voterp_voter_t_f7f020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voterprojection",
            index=models.Index(
                fields=["run", "voter_type"], name="core_voterp_run_id_d896ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voterprojection",
            unique_together={("run", "voter_type", "voter_id")},
        ),
    ]
