# Generated by Django 5.1.7 on 2026-01-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_voterclusterrun_votercluster_voterprojection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticiaProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projection_x",
                    models.FloatField(help_text="X coordinate in PCA space"),
                ),
                (
                    "projection_y",
                    models.FloatField(help_text="Y coordinate in PCA space"),
                ),
                (
                    "n_votes",
                    models.IntegerField(
                        help_text="Total votes received by this noticia"
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_projections",
                        to="core.noticia",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noticia_projections",
                        to="core.voterclusterrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["run"], name="core_notici_run_id_b6fca8_idx")
                ],
                "unique_together": {("run", "noticia")},
            },
        ),
    ]
