# Generated by Django 5.1.7 on 2026-01-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_noticiaprojection"),
    ]

    operations = [
        migrations.AddField(
            model_name="votercluster",
            name="description_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the LLM description was generated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="votercluster",
            name="llm_description",
            field=models.TextField(
                blank=True, help_text="LLM-generated cluster description", null=True
            ),
        ),
        migrations.AddField(
            model_name="votercluster",
            name="llm_name",
            field=models.CharField(
                blank=True,
                help_text="LLM-generated cluster name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="votercluster",
            name="top_entities_negative",
            field=models.JSONField(
                default=list, help_text="Top entities viewed negatively by this cluster"
            ),
        ),
        migrations.AddField(
            model_name="votercluster",
            name="top_entities_positive",
            field=models.JSONField(
                default=list, help_text="Top entities viewed positively by this cluster"
            ),
        ),
    ]
