# Generated by Django 5.1.7 on 2026-01-18 21:25

from django.db import migrations, models
import unicodedata


def normalize_name(name):
    """Normalize entity name: lowercase, no accents."""
    nfkd = unicodedata.normalize('NFKD', name)
    ascii_name = ''.join(c for c in nfkd if not unicodedata.combining(c))
    return ascii_name.lower().strip()


def populate_and_merge_entities(apps, schema_editor):
    """
    Populate normalized_name for all entities and merge duplicates.
    """
    Entidad = apps.get_model('core', 'Entidad')
    NoticiaEntidad = apps.get_model('core', 'NoticiaEntidad')

    # Group entities by (normalized_name, tipo)
    from collections import defaultdict
    groups = defaultdict(list)

    for entidad in Entidad.objects.all():
        normalized = normalize_name(entidad.nombre)
        key = (normalized, entidad.tipo)
        groups[key].append(entidad)

    merged_count = 0
    for (normalized, tipo), entities in groups.items():
        if len(entities) == 1:
            # No duplicates, just set normalized_name
            entidad = entities[0]
            entidad.normalized_name = normalized
            entidad.save()
            continue

        # Multiple entities with same normalized name
        # Keep the first one, merge others into it
        canonical = entities[0]
        canonical.normalized_name = normalized
        canonical.save()

        for duplicate in entities[1:]:
            # Update NoticiaEntidad references
            NoticiaEntidad.objects.filter(entidad=duplicate).update(
                entidad=canonical
            )
            # Delete orphaned NoticiaEntidad (duplicates on same noticia)
            # Django's unique_together will handle this via IntegrityError
            # but let's be explicit
            for ne in NoticiaEntidad.objects.filter(entidad=canonical):
                dupes = NoticiaEntidad.objects.filter(
                    noticia=ne.noticia, entidad=canonical
                ).exclude(pk=ne.pk)
                dupes.delete()

            duplicate.delete()
            merged_count += 1

    print(f"Merged {merged_count} duplicate entities")


def reverse_migration(apps, schema_editor):
    """No-op reverse - can't un-merge entities."""
    pass


class Migration(migrations.Migration):
    # Disable transaction to allow constraint after data modification
    atomic = False

    dependencies = [
        ("core", "0016_add_cluster_llm_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="entidad",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized name for deduplication (lowercase, no accents)",
                max_length=255,
            ),
        ),
        migrations.RunPython(populate_and_merge_entities, reverse_migration),
        migrations.AddConstraint(
            model_name="entidad",
            constraint=models.UniqueConstraint(
                fields=("normalized_name", "tipo"), name="unique_normalized_entity"
            ),
        ),
    ]
