# Generated by Django 5.1.7 on 2026-01-19 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_reengagementemaillog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Public alias shown on cluster map",
                        max_length=30,
                    ),
                ),
                (
                    "show_alias_on_map",
                    models.BooleanField(
                        default=True, help_text="Display alias on cluster visualization"
                    ),
                ),
                (
                    "weekly_email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive weekly emails with news in your area of interest",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="core_userpr_user_id_830b32_idx")
                ],
            },
        ),
    ]
