# Generated by Django 5.1.7 on 2026-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="show_alias_on_map",
            field=models.BooleanField(
                default=False, help_text="Display alias on cluster visualization"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weekly_email_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Receive weekly emails with news in your area of interest",
            ),
        ),
    ]
