# Generated by Django 5.1.7 on 2026-01-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_change_userprofile_defaults_to_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="enlace",
            field=models.URLField(
                help_text="Original news article URL", max_length=2000, unique=True
            ),
        ),
    ]
