# Generated by Django 5.1.7 on 2026-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_noticia_enlace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterNameCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of sorted noticia IDs + entity names",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "noticia_ids",
                    models.JSONField(help_text="Sorted list of top noticia IDs used"),
                ),
                (
                    "entities_positive",
                    models.JSONField(help_text="Sorted list of positive entity names"),
                ),
                (
                    "entities_negative",
                    models.JSONField(help_text="Sorted list of negative entity names"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("use_count", models.IntegerField(default=1)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="After this date, regenerate even if content matches"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Name Cache",
                "verbose_name_plural": "Cluster Name Caches",
            },
        ),
    ]
