# Generated by Django 6.0.1 on 2026-02-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_cluster_name_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reengagement_email_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive re-engagement emails when inactive"
            ),
        ),
    ]
